Usys.Monitor.WebShell/Controllers/DocGenServerHealthController.cs
using System.Web.Mvc;

namespace Usys.Monitor.WebShell.Controllers
{
    public class DocGenServerHealthController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Usys.Monitor.WebShell/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Usys.Monitor.WebShell.Data;

namespace Usys.Monitor.WebShell.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult GetWcfServerProcessorHealth()
        {
            try
            {
                var repository = new Repository();

                var summaries = repository.MvcProcessInfoDaySummaries.ToList();

                return Json(new
                {
                    AverageProcessorUsage = Convert.ToInt32(summaries.Average(r => r.AverageProcessorUsage)),
                    MaximumProcessorUsage = Convert.ToInt32(summaries.Average(r => r.MaximumProcessorUsage)),
                    AverageMemoryUsage = Convert.ToInt32(summaries.Average(r => r.AverageMemoryUsage) / 1024 / 1024),
                    MaximumMemoryUsage = Convert.ToInt32(summaries.Average(r => r.MaximumMemoryUsage) / 1024 / 1024)
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { AverageProcessorUsage = 100 }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetMvcServerProcessorHealth()
        {
            try
            {
                var repository = new Repository();

                var summaries = repository.MvcProcessInfoDaySummaries.ToList();

                return Json(new
                {
                    AverageProcessorUsage = Convert.ToInt32(summaries.Average(r => r.AverageProcessorUsage)),
                    MaximumProcessorUsage = Convert.ToInt32(summaries.Average(r => r.MaximumProcessorUsage)),
                    AverageMemoryUsage = Convert.ToInt32(summaries.Average(r => r.AverageMemoryUsage) / 1024 / 1024),
                    MaximumMemoryUsage = Convert.ToInt32(summaries.Average(r => r.MaximumMemoryUsage) / 1024 / 1024),
                    ServerCount = summaries.GroupBy(m => m.MachineName).Count(),
                    InstanceCount = summaries.Count()
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new
                {
                    AverageProcessorUsage = 0,
                    MaximumProcessorUsage = 0,
                    AverageMemoryUsage = 0,
                    MaximumMemoryUsage = 0
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Usys.Monitor.WebShell/Controllers/MainController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Usys.Monitor.WebShell.Data;
using WebGrease;

namespace Usys.Monitor.WebShell.Controllers
{
    public class MainController : Controller
    {
        public ActionResult Index()
        {
            var repository = new Repository();

            var servers = repository.ServerConfigs.ToList();

            return View(servers);
        }

        public ActionResult ServerLastMinutes(string id)
        {
            return PartialView("_ServerLastHour", id);
        }

        public ActionResult RefreshMvcData()
        {
            var repository = new Repository();

            var averages = repository.GeneralSystemInfoCurrents.Where(s => s.IsMvcServer).ToList();

            return Json(averages, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RefreshWcfData()
        {
            var repository = new Repository();

            var averages = repository.GeneralSystemInfoCurrents.Where(s => s.IsWcfServer).ToList();

            return Json(averages, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RefreshLastHour(string id)
        {
            var repository = new Repository();

            var records = repository.GeneralSystemInfoLastMinutes.Where(s => s.MachineName == id).ToList().OrderBy(s => s.ElapsedSeconds);

            return Json(records, JsonRequestBehavior.AllowGet);
        }
    }
}

Usys.Monitor.WebShell/Controllers/MvcServerHealthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Usys.Monitor.WebShell.Data;
using Usys.Monitor.WebShell.Data.Model;

namespace Usys.Monitor.WebShell.Controllers
{
    public class MvcServerHealthController : Controller
    {
        public ActionResult Index()
        {
            var repository = new Repository();

            var servers = repository.MvcServerConfigs.OrderBy(m => m.MachineName).ToList();

            return View(servers);
        }

        public ActionResult ServerInfo(string id)
        {
            var repository = new Repository();

            var servers = new List<string>();

            if (!string.IsNullOrWhiteSpace(id))
            {
                //return the detail view
                return PartialView("_ServerInfoDetail", id);
            }

            servers.AddRange(repository.MvcServerConfigs.Select(m => m.MachineName));
            return PartialView("_ServerInfo", servers);

        }

        public ActionResult AverageProcessorUsage(string id)
        {
            var repository = new Repository();

            var lower = DateTime.UtcNow.AddDays(-1);

            var hours = repository.MvcProcessInfoHours
                .Where(e => e.MachineName == id)
                .Where(e => e.CreationDateTime > lower)
                .Select(e => new { e.AverageProcessorUsage, e.MaximumProcessorUsage, e.CreationDateTime })
                .ToList();

            var result = Json(hours, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }

        public ActionResult AverageMemoryUsage(string id)
        {
            var repository = new Repository();

            var lower = DateTime.UtcNow.AddDays(-1);

            var hours = repository.MvcProcessInfoHours
                .Where(e => e.MachineName == id)
                .Where(e => e.CreationDateTime > lower)
                .Select(e => new
                {
                    AverageMemoryUsage = e.AverageMemoryUsage / 1024 / 1024,
                    MaximumMemoryUsage = e.MaximumMemoryUsage / 1024 / 1024,
                    e.CreationDateTime
                })
                .ToList();

            var result = Json(hours, JsonRequestBehavior.AllowGet);
            result.MaxJsonLength = int.MaxValue;
            return result;
        }
    }
}

Usys.Monitor.WebShell/Controllers/TelnetServerHealthController.cs
using System.Web.Mvc;

namespace Usys.Monitor.WebShell.Controllers
{
    public class TelnetServerHealthController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Usys.Monitor.WebShell/Controllers/WcfServerHealthController.cs
using System.Web.Mvc;

namespace Usys.Monitor.WebShell.Controllers
{
    public class WcfServerHealthController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Usys.Monitor.WebShell/Views/DocGenServerHealth/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>title</h2>

Usys.Monitor.WebShell/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>Monitor server health</h3>

<p></p>

Usys.Monitor.WebShell/Views/Home/Index.cshtml
@using Kendo.Mvc.UI
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Usys System Monitor</h1>
    @*<p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Mvc @DateTime.Now.ToShortDateString()</h2>
        <p>
            <table class="table" id="MvcInfoList" data-url="@Url.Action("GetMvcServerProcessorHealth")">
                <tr>
                    <td>Avg CPU</td>
                    <td><span id="MvcAverageProcessorUsageLabel">???</span> %</td>
                </tr>
                <tr>
                    <td>Max CPU</td>
                    <td><span id="MvcMaximumProcessorUsageLabel">???</span> %</td>
                </tr>
                <tr>
                    <td>Avg MEM</td>
                    <td><span id="MvcAverageMemoryUsageLabel">???</span> Mb</td>
                </tr>
                <tr>
                    <td>Max MEM</td>
                    <td><span id="MvcMaximumMemoryUsageLabel">???</span> Mb</td>
                </tr>
                <tr>
                    <td>Servers</td>
                    <td><span id="MvcServerCountLabel">???</span></td>
                </tr>
                <tr>
                    <td>Instances</td>
                    <td><span id="MvcInstanceCountLabel">???</span></td>
                </tr>
            </table>
        </p>
        <p>
            @Html.ActionLink("Details »", "Index", "MvcServerHealth", null, new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-md-3">
        <h2>Wcf Health</h2>
        <p>@Html.ActionLink("Details »", "Index", "WcfServerHealth", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-3">
        <h2>Telnet Health</h2>
        <p>@Html.ActionLink("Details »", "Index", "TelnetServerHealth", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-3">
        <h2>DocGen Health</h2>
        <p>@Html.ActionLink("Details »", "Index", "DocGenServerHealth", null, new { @class = "btn btn-default" })</p>
    </div>
</div>

@section scripts
{
    <script>
        $(function () {
            UpdateMvcHealthGauge();
            UpdateWcfHealthGauge();
            UpdateTelnetHealthGauge();
            UpdateDocGenHealthGauge();

            setInterval(UpdateMvcHealthGauge, 60000);
            setInterval(UpdateWcfHealthGauge, 60000);
            setInterval(UpdateTelnetHealthGauge, 60000);
            setInterval(UpdateDocGenHealthGauge, 60000);
        });

        function UpdateMvcHealthGauge() {
            $("#MvcAverageProcessorUsageLabel").html('???');
            $("#MvcMaximumProcessorUsageLabel").html('???');
            $("#MvcAverageMemoryUsageLabel").html('???');
            $("#MvcMaximumMemoryUsageLabel").html('???');

            var url = $('#MvcInfoList').data('url');
            $.ajax({
                url: url,
                dataType: 'JSON',
                type: 'GET',
                success: function (data) {
                    $("#MvcAverageProcessorUsageLabel").html(data.AverageProcessorUsage);
                    $("#MvcMaximumProcessorUsageLabel").html(data.MaximumProcessorUsage);
                    $("#MvcAverageMemoryUsageLabel").html(data.AverageMemoryUsage);
                    $("#MvcMaximumMemoryUsageLabel").html(data.MaximumMemoryUsage);
                    $("#MvcServerCountLabel").html(data.ServerCount);
                    $("#MvcInstanceCountLabel").html(data.InstanceCount);
                },
                error: function (err) {
                    alert(err.responseText);
                }
            });
        }

        function UpdateWcfHealthGauge() {
            //var url = $('#WcfHealthGauge').data('url');
            //$.ajax({
            //    url: url,
            //    dataType: 'JSON',
            //    type: 'GET',
            //    success: function (data) {
            //        $("#WcfHealthGauge").data("kendoRadialGauge").value(data.AverageProcessorUsage);
            //    },
            //    error: function (err) {
            //        alert(err.responseText);
            //    }
            //});
        }

        function UpdateTelnetHealthGauge() {

        }

        function UpdateDocGenHealthGauge() {

        }
    </script>
}

Usys.Monitor.WebShell/Views/Main/Index.cshtml
@model List<Usys.Monitor.WebShell.Data.Model.ServerConfig>
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";

    var mvcServers = Model.Where(s => s.IsMvcServer).ToList();
    var wcfServers = Model.Where(s => s.IsWcfServer).ToList();
}

@Html.Partial("_Menu", Model)

@Html.Partial("_WcfOverview", wcfServers)
@Html.Partial("_MvcOverview", mvcServers)

Usys.Monitor.WebShell/Views/Main/_MvcOverview.cshtml
@using Kendo.Mvc.UI
@model List<Usys.Monitor.WebShell.Data.Model.ServerConfig>


<table style="width: 100%;">
    <tr>
        @foreach (var server in Model)
        {
            <td style="width: @(100 / Model.Count)%;">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">@server.MachineName</h3>
                    </div>
                    <div class="panel-body">
                        @{
                            Html.Kendo().RadialGauge().Name("Mvc-" + server.MachineName + "-Gauge")
                                .Scale(config => config.Min(0).Max(100)).RenderAs(RenderingMode.Canvas)
                                .Render();
                        }

                        <div class="progress">
                            <div id="@("Mvc-" + server.MachineName + "-AverageProgressBar")" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%; min-width: 20px;">
                                ???
                            </div>
                        </div>
                        <div class="progress">
                            <div id="@("Mvc-" + server.MachineName + "-MaximumProgressBar")" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%; min-width: 20px;">
                                ???
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="btn-group">
                            <div data-function="OpenWindow" class="btn btn-default" data-title="@server.MachineName" data-url="@Url.Action("ServerLastMinutes", new { id = server.MachineName })">Last minutes</div>
                        </div>
                    </div>
                </div>
            </td>
        }
    </tr>
</table>

<script>
    $(function () {
        $('#MvcServersGeneralOverview').kendoWindow();

        setInterval(function () { RefreshMvcData(); }, 1000);

        RefreshMvcData();
    });

    function RefreshMvcData() {
        $.ajax({
            url: '@Url.Action("RefreshMvcData")',
            dataType: 'JSON',
            success: function (data) {
                $.each(data, function (index, server) {
                    $('#Mvc-' + server.MachineName + '-Gauge').data('kendoRadialGauge').value(server.AverageProcessorUsage);
                    $('#Mvc-' + server.MachineName + '-AverageProgressBar').text(server.AverageProcessorUsage + '%');
                    $('#Mvc-' + server.MachineName + '-AverageProgressBar').css('width', server.AverageProcessorUsage + '%');
                    $('#Mvc-' + server.MachineName + '-MaximumProgressBar').text(server.MaximumProcessorUsage + '%');
                    $('#Mvc-' + server.MachineName + '-MaximumProgressBar').css('width', server.MaximumProcessorUsage + '%');
                });
            }
        });
    }
</script>

Usys.Monitor.WebShell/Views/Main/_ServerLastHour.cshtml
@using Kendo.Mvc.UI
@using Usys.Monitor.WebShell.Data.Model
@model string

@{
    var id = Guid.NewGuid().ToString("D");
}

@{
    Html.Kendo().Chart<GeneralSystemInfoLastMinute>().Name(id)
        .Series(config =>
        {
            config.Column(m => m.AverageProcessorUsage).Name("Avg");
            config.Column(m => m.MaximumProcessorUsage).Name("Max");
        })
        .ValueAxis(axis => axis.Numeric().Min(0).Max(100))
        .CategoryAxis(axis => axis.Name("label-axis").Categories(m => m.ElapsedSeconds).Labels(labels => labels.Template("#= kendo.toString(new Date(value * 1000), 'HH:mm:ss') #").Rotation(90)))        
        .AutoBind(true)
        .DataSource(config => config.Read(a => a.Action("RefreshLastHour", "Main", new { id = Model })))
        .Tooltip(tooltip => tooltip.Visible(true).Template("#= value #%"))
        .Render();
}

<script>
    $(function () {
        setInterval(function () { $('#@id').data('kendoChart').dataSource.read(); }, 5000);
    });
</script>

Usys.Monitor.WebShell/Views/Main/_WcfOverview.cshtml
@using Kendo.Mvc.UI
@model List<Usys.Monitor.WebShell.Data.Model.ServerConfig>
<table style="width: 100%;">
    <tr>
        @foreach (var server in Model)
        {
            <td style="width: @(100 / Model.Count)%;">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">@server.MachineName</h3>
                    </div>
                    <div class="panel-body">
                        @{
            Html.Kendo().RadialGauge().Name("Wcf-" + server.MachineName + "-Gauge")
                .Scale(config => config.Min(0).Max(100)).RenderAs(RenderingMode.Canvas)
                .Render();
                        }

                        <div class="progress">
                            <div id="@("Wcf-" + server.MachineName + "-AverageProgressBar")" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%; min-width: 20px;">
                                ???
                            </div>
                        </div>
                        <div class="progress">
                            <div id="@("Wcf-" + server.MachineName + "-MaximumProgressBar")" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%; min-width: 20px;">
                                ???
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="btn-group">
                            <div data-function="OpenWindow" class="btn btn-default" data-title="@server.MachineName" data-url="@Url.Action("ServerLastMinutes", new { id = server.MachineName })">Last minutes</div>
                        </div>
                    </div>
                </div>
            </td>
        }
    </tr>
</table>

<script>
    $(function () {
        $('#WcfServersGeneralOverview').kendoWindow();

        setInterval(function () { RefreshWcfData(); }, 1000);

        RefreshWcfData();
    });

    function RefreshWcfData() {
        $.ajax({
            url: '@Url.Action("RefreshWcfData")',
            dataType: 'JSON',
            success: function (data) {
                $.each(data, function (index, server) {
                    $('#Wcf-' + server.MachineName + '-Gauge').data('kendoRadialGauge').value(server.AverageProcessorUsage);
                    $('#Wcf-' + server.MachineName + '-AverageProgressBar').text(server.AverageProcessorUsage + '%');
                    $('#Wcf-' + server.MachineName + '-AverageProgressBar').css('width', server.AverageProcessorUsage + '%');
                    $('#Wcf-' + server.MachineName + '-MaximumProgressBar').text(server.MaximumProcessorUsage + '%');
                    $('#Wcf-' + server.MachineName + '-MaximumProgressBar').css('width', server.MaximumProcessorUsage + '%');
                });
            }
        });
    }
</script>

Usys.Monitor.WebShell/Views/MvcServerHealth/Index.cshtml
@using Kendo.Mvc.UI
@model List<Usys.Monitor.WebShell.Data.Model.MvcServerConfig>

@{
    ViewBag.Title = "Mvc overview";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Mvc Servers details</h3>
            </div>
            <div class="panel-body">
                @{
                    Html.Kendo().TabStrip().Name("ServerTabStrip")
                        .Items(items =>
                        {
                            items.Add().Text("All").Selected(true).LoadContentFrom(Url.Action("ServerInfo"));
                            foreach (var server in Model)
                            {
                                items.Add().Text(server.MachineName).LoadContentFrom(Url.Action("ServerInfo", new { id = server.MachineName })).HtmlAttributes(new { id = server.MachineName + "-Tab" });
                            }
                        })
                        .Animation(a => a.Enable(true))
                        .Render();
                }
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(function () {
            InitializeServerClick();
        });

        function InitializeServerClick() {
            $(document).on('click', 'a[data-server]', null, function (event) {
                event.preventDefault();

                $('#ServerTabStrip').data('kendoTabStrip').activateTab($('#' + $(this).data('server') + '-Tab'));
            });
        }
    </script>
}

Usys.Monitor.WebShell/Views/MvcServerHealth/_ServerInfo.cshtml
@using Kendo.Mvc.UI
@using Usys.Monitor.WebShell.Data.Model
@model List<string>

@foreach (var server in Model)
{
    Html.Kendo().Chart<MvcProcessInfoHour>().Name(Guid.NewGuid().ToString("D"))
        .Series(config =>
        {
            config.Column(m => m.AverageProcessorUsage).Name("Avg");
            config.Column(m => m.MaximumProcessorUsage).Name("Max");
        })
        .Title(server)
        .YAxis(config => config.Numeric().Min(0).Max(100))
        .CategoryAxis(axis => axis.Name("label-axis").Categories(m => m.CreationDateTime).Labels(labels => labels.Template("#= kendo.toString(kendo.parseDate(value),'HH:mm') #")))
        .AutoBind(true)
        .DataSource(config => config.Read(a => a.Action("AverageProcessorUsage", "MvcServerHealth", new { id = server })))
        .Tooltip(tooltip => tooltip.Visible(true).Template("#= value #%"))
        .Events(events =>
        {
            events.PlotAreaClick("function(){openWindow('" + Url.Action("ServerInfo", new { id = server }) + "', '" + server + "')}");
        })
        .Render();
}

Usys.Monitor.WebShell/Views/MvcServerHealth/_ServerInfoDetail.cshtml
@using Kendo.Mvc.UI
@using Usys.Monitor.WebShell.Data.Model
@model string

@{
    Html.Kendo().Chart<MvcProcessInfoHour>().Name(Guid.NewGuid().ToString("D"))
        .Series(config =>
        {
            config.Column(m => m.AverageProcessorUsage).Name("Avg");
            config.Column(m => m.MaximumProcessorUsage).Name("Max");
        })
        .CategoryAxis(axis => axis.Categories(m => m.CreationDateTime).Labels(labels => labels.Template("#= kendo.toString(kendo.parseDate(value),'HH:mm') #")))
        .ValueAxis(axis => axis.Numeric().Max(100).Min(0).Labels(labels => labels.Template("#= value #%")))
        .Title("MVC Processes - CPU")
        .AutoBind(true)
        .DataSource(config => config.Read(a => a.Action("AverageProcessorUsage", "MvcServerHealth", new { id = Model })))
        .Tooltip(tooltip => tooltip.Visible(true).Template("#= value #%"))
        .Render();

    Html.Kendo().Chart<MvcProcessInfoHour>().Name(Guid.NewGuid().ToString("D"))
        .Series(config =>
        {
            config.Column(m => m.AverageMemoryUsage).Name("Avg");
            config.Column(m => m.MaximumMemoryUsage).Name("Max");
        })
        .CategoryAxis(axis => axis.Categories(m => m.CreationDateTime).Labels(labels => labels.Template("#= kendo.toString(kendo.parseDate(value),'HH:mm') #")))
        .ValueAxis(axis => axis.Numeric().Min(0).Labels(labels => labels.Template("#= value #Mb")))
        .Title("MVC Processes - Memory")
        .AutoBind(true)
        .DataSource(config => config.Read(a => a.Action("AverageMemoryUsage", "MvcServerHealth", new { id = Model })))
        .Tooltip(tooltip => tooltip.Visible(true).Template("#= value #Mb"))
        .Render();
}

Usys.Monitor.WebShell/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Usys System Monitor</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kendo")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/kendoScripts")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Usys System Monitor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Usys System Monitor</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Usys.Monitor.WebShell/Views/Shared/_Menu.cshtml
@using Kendo.Mvc.UI
@model List<Usys.Monitor.WebShell.Data.Model.ServerConfig>
    @{
        Html.Kendo().Menu().Name("MainMenu")
            .Items(items =>
            {
                items.Add().Text("Start");

                items.Add().Text("Mvc").Items(subs =>
                {
                    subs.Add().Text("CPU Overview").HtmlAttributes(new { data_url = Url.Action("ServerInfo", "MvcServerHealth") });
                    subs.Add().Separator(true);
                    foreach (var server in Model.Where(s => s.IsMvcServer).OrderBy(s => s.MachineName))
                    {
                        subs.Add().Text(server.MachineName).HtmlAttributes(new { data_url = Url.Action("ServerInfo", "MvcServerHealth", new { id = server.MachineName }) });
                    }
                });

                items.Add().Text("Wcf");

                items.Add().Text("Scanner");

                items.Add().Text("DocGen");

                items.Add().Text("Window").Items(subs =>
                {
                    subs.Add().Text("Close all windows").HtmlAttributes(new { data_function = "closeAllWindows" });
                });
            })
            .Render();
    }

Usys.Monitor.WebShell/Views/TelnetServerHealth/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>title</h2>

Usys.Monitor.WebShell/Views/WcfServerHealth/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>title</h2>